# -*- coding: utf-8 -*-
"""Number of People Born

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BNC37xkHKkqPeZBaAE_2JNKRtVCuiVu_
"""

str1 = input("Please insert a year")
a = int(str1)
b2020 = 18.077
b2019 = 18.282
b2018 = 18.486
b2017 = 18.682
b2016 = 18.879
b2015 = 19.075
b2014 = 19.272
b2013 = 19.468
b2012 = 19.642
b2011 = 19.817
b2010 = 19.991
b2009 = 20.166
b2008 = 20.340
b2007 = 20.475
b2006 = 20.611
b2005 = 20.746
b2004 = 20.882
b2003 = 21.017
b2002 = 21.256
b2001 = 21.495
b2000 = 21.733
if a == 2020:
  d = ((7800000000/1000)*b2020)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/366
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2019:
  d = ((7700000000/1000)*b2019)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/365
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2018:
  d = ((7600000000/1000)*b2018)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/365
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2017:
  d = ((7500000000/1000)*b2017)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/365
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2016:
  d = ((7500000000/1000)*b2016)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/366
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2015:
  d = ((7400000000/1000)*b2015)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/365
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)
elif a == 2014:
  d = ((7300000000/1000)*b2014)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/365
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2013:
  d = ((7200000000/1000)*b2013)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/365
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2012:
  d = ((7100000000/1000)*b2012)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/366
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2011:
  d = ((7000000000/1000)*b2011)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/365
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2010:
  d = ((6900000000/1000)*b2010)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/365
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2009:
  d = ((6800000000/1000)*b2009)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/365
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2008:
  d = ((6800000000/1000)*b2008)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/366
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2007:
  d = ((6700000000/1000)*b2007)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/365
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2006:
  d = ((6600000000/1000)*b2006)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/365
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2005:
  d = ((6500000000/1000)*b2005)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/365
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2004:
  d = ((6500000000/1000)*b2004)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/366
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2003:
  d = ((6400000000/1000)*b2003)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/365
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2002:
  d = ((6300000000/1000)*b2002)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/365
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2001:
  d = ((6200000000/1000)*b2001)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/365
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

elif a == 2000:
  d = ((6100000000/1000)*b2016)
  print("The Total People Born is:",d)
  c = d/12
  print("The Total Amount Of People Born Each Month Is:",c)
  e = d/366
  print("The Total Amount Of People Born Each Day Is:",e)
  f = e/1440
  print("The Total Amount Of People Born Each Minute Is:",f)
  g = f/60
  print("The Total Amount Of People Born Each Second Is:",g)

else: 
  print("Does Not Compute")
  
